# Generated by Django 5.2 on 2025-06-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0011_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='batch',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foresight_app.class'),
        ),
    ]
