# Generated by Django 5.2 on 2025-06-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0012_studentregistration_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='batch',
        ),
    ]
