# Generated by Django 5.2 on 2025-06-26 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0013_remove_studentregistration_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='class_name',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=9)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foresight_app.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foresight_app.studentregistration')),
            ],
        ),
    ]
