# Generated by Django 5.2 on 2025-06-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0014_remove_studentregistration_class_name_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perid_1', models.BooleanField()),
                ('perid_2', models.BooleanField()),
                ('perid_3', models.BooleanField()),
                ('perid_4', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foresight_app.studentregistration')),
            ],
        ),
    ]
