# Generated by Django 5.2 on 2025-06-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0015_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='perid_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='perid_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='perid_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='perid_4',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
