# Generated by Django 5.2 on 2025-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0017_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
