# Generated by Django 5.2 on 2025-06-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foresight_app', '0018_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
